import {
  Group,
  Entity,
  AssetOrProject,
  IntercompanyTransaction,
  EliminationEntry,
  DebtFacility,
  CapexItem,
  CostAllocationRule,
  ManagementFeeRule,
  ShareholderCapital,
  FXRate,
} from "./types";

export const DEMO_GROUP: Group = {
  id: "grp_atlas_01",
  name: "Atlas Alliance Group",
  code: "AAG",
  consolidationCurrency: "MAD",
  description: "Groupe diversifié multi-entités et multi-actifs (Holding, Filiales Opérationnelles, SPVs)",
  headquartersCountry: "Maroc",
  createdAt: "2024-01-15T00:00:00Z",
};

export const DEMO_FX_RATES: FXRate[] = [
  { pair: "EUR/MAD", fromCurrency: "EUR", toCurrency: "MAD", rate: 10.85, effectiveMonth: "2026-09", manualOverride: false },
  { pair: "USD/MAD", fromCurrency: "USD", toCurrency: "MAD", rate: 9.95, effectiveMonth: "2026-09", manualOverride: false },
  { pair: "GBP/MAD", fromCurrency: "GBP", toCurrency: "MAD", rate: 12.80, effectiveMonth: "2026-09", manualOverride: false },
  { pair: "XOF/MAD", fromCurrency: "XOF", toCurrency: "MAD", rate: 0.0165, effectiveMonth: "2026-09", manualOverride: false },
  { pair: "MAD/MAD", fromCurrency: "MAD", toCurrency: "MAD", rate: 1.0, effectiveMonth: "2026-09", manualOverride: false },
];

export const DEMO_ENTITIES: Entity[] = [
  {
    id: "ent_holding",
    groupId: "grp_atlas_01",
    parentId: null,
    name: "Atlas Holding Corp",
    legalName: "Atlas Alliance Holding SA",
    code: "HOLD",
    type: "holding",
    country: "Maroc",
    functionalCurrency: "MAD",
    reportingCurrency: "MAD",
    ownershipPercentage: 100,
    consolidationMethod: "full",
    operationalStatus: "operating",
    legalStatus: "active",
    taxId: "ICE-00192847100029",
    sector: "Investissement & Services Centraux",
    description: "Société mère tête de groupe, détentrice des titres et des services partagés",
    financials: {
      revenue: 1250000, // Management fees refacturés aux filiales
      ebitda: 420000,
      ebitdaMargin: 33.6,
      cash: 2450000,
      operationalMinimum: 500000,
      deployableCash: 1950000,
      grossDebt: 1500000, // Dette holding
      netDebt: -950000, // Excédent net
      workingCapital: 350000,
      dso: 35,
      dpo: 30,
      arOverdue: 120000,
      apBalance: 85000,
      capexCommitted: 150000,
      budgetVariancePct: -1.2,
      runwayMonths: 24,
      cashTrendWeekly: [2450, 2430, 2400, 2460, 2420, 2400, 2380, 2360, 2350, 2340, 2320, 2300, 2290],
    },
    healthPillars: {
      liquidity: { status: "healthy", reason: "Réserves confortables (2,45M MAD), aucun impayé critique" },
      profitability: { status: "healthy", reason: "Frais de gestion équilibrés, marge de holding conforme" },
      workingCapital: { status: "healthy", reason: "Flux d'honoraires réguliers" },
      budgetControl: { status: "healthy", reason: "Dépenses de siège conformes à l'enveloppe (-1.2%)" },
      debtSolvency: { status: "healthy", reason: "Ratio dette nette / EBITDA négatif (trésorerie excédentaire)" },
      dataQuality: { status: "healthy", reason: "Clôture comptable complète à J+3" },
    },
    dataQuality: {
      lastUpdate: "2026-09-25",
      missingPeriodsCount: 0,
      unmatchedIntercompanyCount: 0,
      bankFeedConnected: true,
      budgetConfigured: true,
      freshnessScorePct: 100,
    },
  },
  {
    id: "ent_alpha",
    groupId: "grp_atlas_01",
    parentId: "ent_holding",
    name: "Entity Alpha (Tech & Services)",
    legalName: "Alpha Solutions & Infrastructures SARL",
    code: "ALPHA",
    type: "subsidiary",
    country: "Maroc",
    functionalCurrency: "MAD",
    reportingCurrency: "MAD",
    ownershipPercentage: 100,
    consolidationMethod: "full",
    operationalStatus: "operating",
    legalStatus: "active",
    taxId: "ICE-00238194000018",
    sector: "Solutions & Services Numériques",
    description: "Filiale historique à forte rentabilité et génération de cash structurelle",
    financials: {
      revenue: 28500000,
      ebitda: 7200000,
      ebitdaMargin: 25.26,
      cash: 4800000,
      operationalMinimum: 1200000,
      deployableCash: 3600000,
      grossDebt: 3200000,
      netDebt: -1600000, // Excédent net
      workingCapital: 2100000,
      dso: 42,
      dpo: 45,
      arOverdue: 680000,
      apBalance: 1250000,
      capexCommitted: 650000,
      budgetVariancePct: 3.4,
      runwayMonths: 18,
      cashTrendWeekly: [4800, 4850, 4920, 5010, 5100, 5150, 5240, 5300, 5390, 5450, 5520, 5600, 5700],
    },
    healthPillars: {
      liquidity: { status: "healthy", reason: "Cash libre élevé (3,6M MAD mobilisables), autofinancement solide" },
      profitability: { status: "healthy", reason: "Marge EBITDA à 25.3%, supérieure au secteur" },
      workingCapital: { status: "healthy", reason: "DSO maîtrisé à 42 jours" },
      budgetControl: { status: "healthy", reason: "Léger dépassement de CA (+3.4%) en ligne avec la croissance" },
      debtSolvency: { status: "healthy", reason: "Dette résiduelle amortissable sans tension" },
      dataQuality: { status: "healthy", reason: "Connecteur ERP actif, imports quotidiens" },
    },
    dataQuality: {
      lastUpdate: "2026-09-27",
      missingPeriodsCount: 0,
      unmatchedIntercompanyCount: 1, // Intentional mismatch with Beta
      bankFeedConnected: true,
      budgetConfigured: true,
      freshnessScorePct: 98,
    },
  },
  {
    id: "ent_beta",
    groupId: "grp_atlas_01",
    parentId: "ent_holding",
    name: "Entity Beta (Distribution Europe)",
    legalName: "Beta Logistics & Trading SAS",
    code: "BETA",
    type: "subsidiary",
    country: "France",
    functionalCurrency: "EUR",
    reportingCurrency: "MAD",
    ownershipPercentage: 80,
    consolidationMethod: "full",
    operationalStatus: "operating",
    legalStatus: "active",
    taxId: "FR-8892104921",
    sector: "Distribution Internationale",
    description: "Filiale de négoce et distribution. Rentable sur le papier mais confrontée à un retard de recouvrement critique (DSO 88 jours)",
    financials: {
      revenue: 18200000, // En équivalent MAD (1.677M EUR)
      ebitda: 3100000,
      ebitdaMargin: 17.03,
      cash: 420000, // Alerte tension
      operationalMinimum: 800000,
      deployableCash: 0, // Déficit de couverture sous le seuil min
      grossDebt: 4500000,
      netDebt: 4080000,
      workingCapital: 6800000, // BFR hypertrophié par créances
      dso: 88, // Alerte rouge recouvrement
      dpo: 38,
      arOverdue: 6400000, // Créances en souffrance
      apBalance: 2900000,
      capexCommitted: 320000,
      budgetVariancePct: -8.5,
      runwayMonths: 1.4, // Moins de 6 semaines !
      cashTrendWeekly: [420, 380, 310, 190, 80, -45, -160, -290, -420, -530, -610, -700, -780], // Risque de rupture en semaine 4-6
    },
    healthPillars: {
      liquidity: { status: "critical", reason: "Rupture de cash projetée sous 4 semaines sans relance ou soutien intercompany" },
      profitability: { status: "watch", reason: "Marge comptable correcte (17%) mais non convertie en cash" },
      workingCapital: { status: "critical", reason: "DSO excessif (88j) et 6,4M MAD de créances bloquées" },
      budgetControl: { status: "watch", reason: "Charges logistiques supérieures aux prévisions (-8.5%)" },
      debtSolvency: { status: "watch", reason: "Service d'emprunt bancaire EUR pesant sur le disponible" },
      dataQuality: { status: "watch", reason: "Écart de réconciliation intercompany de 20 000 MAD avec Alpha" },
    },
    dataQuality: {
      lastUpdate: "2026-09-26",
      missingPeriodsCount: 0,
      unmatchedIntercompanyCount: 1, // Intentional mismatch
      bankFeedConnected: true,
      budgetConfigured: true,
      freshnessScorePct: 88,
    },
  },
  {
    id: "ent_gamma",
    groupId: "grp_atlas_01",
    parentId: "ent_holding",
    name: "Entity Gamma (Industrie & Manufacturing)",
    legalName: "Gamma Industrial & Manufacturing SA",
    code: "GAMMA",
    type: "subsidiary",
    country: "Maroc",
    functionalCurrency: "MAD",
    reportingCurrency: "MAD",
    ownershipPercentage: 100,
    consolidationMethod: "full",
    operationalStatus: "operating",
    legalStatus: "active",
    taxId: "ICE-00109283740192",
    sector: "Transformation & Industrie Lourde",
    description: "Activité industrielle à marge modérée supportant un important plan d'investissement de modernisation (CAPEX 3,8M MAD)",
    financials: {
      revenue: 14100000,
      ebitda: 920000,
      ebitdaMargin: 6.52, // Marge faible
      cash: 680000,
      operationalMinimum: 600000,
      deployableCash: 80000,
      grossDebt: 5800000, // Forte dette industrielle
      netDebt: 5120000,
      workingCapital: 1950000,
      dso: 55,
      dpo: 65,
      arOverdue: 950000,
      apBalance: 2400000,
      capexCommitted: 3800000, // CAPEX très lourd
      budgetVariancePct: -4.1,
      runwayMonths: 4.5,
      cashTrendWeekly: [680, 640, 590, 510, 480, 430, 390, 350, 320, 290, 270, 250, 220],
    },
    healthPillars: {
      liquidity: { status: "watch", reason: "Marge de manœuvre étroite face aux décaissements CAPEX à venir" },
      profitability: { status: "watch", reason: "Marge EBITDA faible (6.5%), sensibilité aux coûts matières" },
      workingCapital: { status: "watch", reason: "DPO élevé (65j) pour financer le cycle" },
      budgetControl: { status: "watch", reason: "Surcoûts sur les travaux d'installation usine" },
      debtSolvency: { status: "critical", reason: "Ratio Dette / EBITDA > 5.5x, proche du covenant bancaire" },
      dataQuality: { status: "healthy", reason: "Export comptable validé mensuellement" },
    },
    dataQuality: {
      lastUpdate: "2026-09-24",
      missingPeriodsCount: 0,
      unmatchedIntercompanyCount: 0,
      bankFeedConnected: true,
      budgetConfigured: true,
      freshnessScorePct: 92,
    },
  },
  {
    id: "ent_delta",
    groupId: "grp_atlas_01",
    parentId: "ent_holding",
    name: "SPV Delta (Infrastructures Vertes)",
    legalName: "Delta Green Infrastructure SPV LLC",
    code: "DELTA",
    type: "spv",
    country: "Émirats Arabes Unis / International",
    functionalCurrency: "USD",
    reportingCurrency: "MAD",
    ownershipPercentage: 60,
    consolidationMethod: "proportional",
    operationalStatus: "pre_opening",
    legalStatus: "active",
    taxId: "AE-DXB-99210",
    sector: "Énergie & Infrastructures",
    description: "Véhicule d'investissement de projet en phase de développement/pré-ouverture. Aucun CA opérationnel, financé par avance d'actionnaire / prêt intercompany.",
    financials: {
      revenue: 0, // Pré-revenu
      ebitda: -180000, // Coûts d'études et pré-lancement
      ebitdaMargin: 0,
      cash: 720000, // En équivalent MAD (72.3K USD)
      operationalMinimum: 250000,
      deployableCash: 470000,
      grossDebt: 1500000, // Dette d'amorçage envers la Holding
      netDebt: 780000,
      workingCapital: -120000,
      dso: 0,
      dpo: 30,
      arOverdue: 0,
      apBalance: 160000,
      capexCommitted: 2100000, // Budget construction
      budgetVariancePct: 0.8,
      runwayMonths: 7.2,
      cashTrendWeekly: [720, 690, 650, 620, 580, 540, 500, 460, 420, 380, 350, 310, 270],
    },
    healthPillars: {
      liquidity: { status: "watch", reason: "Dépendance aux tirages d'avances de la Holding pour couvrir les jalons" },
      profitability: { status: "watch", reason: "Phase pré-ouverture : aucun produit d'exploitation généré" },
      workingCapital: { status: "healthy", reason: "Engagements fournisseurs séquencés" },
      budgetControl: { status: "healthy", reason: "Respect du calendrier de développement" },
      debtSolvency: { status: "healthy", reason: "Dette 100% intercompany junior, sans risque bancaire tiers" },
      dataQuality: { status: "healthy", reason: "Comptabilité de projet dédiée" },
    },
    dataQuality: {
      lastUpdate: "2026-09-25",
      missingPeriodsCount: 0,
      unmatchedIntercompanyCount: 0,
      bankFeedConnected: true,
      budgetConfigured: true,
      freshnessScorePct: 95,
    },
  },
];

export const DEMO_ASSETS: AssetOrProject[] = [
  {
    id: "ast_alpha_1",
    entityId: "ent_alpha",
    name: "Pôle Cloud & Cyber Infra",
    code: "AST-A1",
    type: "business_unit",
    status: "operating",
    revenue: 16500000,
    costs: 11800000,
    ebitda: 4700000,
    capexBudget: 400000,
    capexSpent: 280000,
    description: "Infrastructures serveurs managées pour comptes institutionnels",
  },
  {
    id: "ast_alpha_2",
    entityId: "ent_alpha",
    name: "Hub Logistique & Intégration",
    code: "AST-A2",
    type: "asset",
    status: "operating",
    revenue: 12000000,
    costs: 9500000,
    ebitda: 2500000,
    capexBudget: 250000,
    capexSpent: 210000,
    description: "Centre de préparation et distribution d'équipements technologiques",
  },
  {
    id: "ast_gamma_1",
    entityId: "ent_gamma",
    name: "Usine Métallurgie & Assemblage",
    code: "AST-G1",
    type: "asset",
    status: "operating",
    revenue: 14100000,
    costs: 13180000,
    ebitda: 920000,
    capexBudget: 3800000,
    capexSpent: 2400000,
    description: "Site industriel principal soumis au programme d'automatisation",
  },
  {
    id: "ast_delta_1",
    entityId: "ent_delta",
    name: "Centrale Solaire & BESS 15MW",
    code: "PRJ-D1",
    type: "project",
    status: "pre_opening",
    revenue: 0,
    costs: 180000,
    ebitda: -180000,
    capexBudget: 2100000,
    capexSpent: 850000,
    description: "Projet de parc photovoltaïque avec stockage batteries en cours de raccordement",
  },
];

// Realistic intercompany transactions including intentional 20,000 MAD mismatch for QA verification!
export const DEMO_INTERCOMPANY_TRANSACTIONS: IntercompanyTransaction[] = [
  {
    id: "ict_001",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_alpha",
    targetEntityId: "ent_beta",
    type: "cost_recharge",
    amount: 500000, // Entity Alpha says receivable is 500,000 MAD
    currency: "MAD",
    convertedAmountMAD: 500000,
    date: "2026-08-15",
    period: "2026-08",
    description: "Refacturation prestations informatiques et licences partagées ERP",
    status: "partial_match", // Intentional discrepancy !
    isRecurring: true,
    reconciliationNotes: "Écart de 20 000 MAD : Beta a comptabilisé 480 000 MAD en déduisant une note de débit non validée",
    discrepancyAmount: 20000,
  },
  {
    id: "ict_002",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_holding",
    targetEntityId: "ent_delta",
    type: "intercompany_loan",
    amount: 1500000,
    currency: "MAD",
    convertedAmountMAD: 1500000,
    date: "2026-04-10",
    period: "2026-Q2",
    description: "Prêt d'actionnaire subordonné pour financement études et pré-travaux SPV Delta",
    status: "eliminated",
    isRecurring: false,
    reconciliationNotes: "Soldes concordants (Actif Holding = Passif SPV Delta)",
    discrepancyAmount: 0,
  },
  {
    id: "ict_003",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_holding",
    targetEntityId: "ent_alpha",
    type: "management_fee",
    amount: 450000,
    currency: "MAD",
    convertedAmountMAD: 450000,
    date: "2026-09-01",
    period: "2026-09",
    description: "Honoraires de direction générale, stratégie et support juridique T3",
    status: "eliminated",
    isRecurring: true,
    reconciliationNotes: "Parfaitement rapproché",
    discrepancyAmount: 0,
  },
  {
    id: "ict_004",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_holding",
    targetEntityId: "ent_beta",
    type: "management_fee",
    amount: 320000,
    currency: "MAD",
    convertedAmountMAD: 320000,
    date: "2026-09-01",
    period: "2026-09",
    description: "Management fees et assistance financière groupe T3",
    status: "eliminated",
    isRecurring: true,
    reconciliationNotes: "Comptabilisé et validé",
    discrepancyAmount: 0,
  },
  {
    id: "ict_005",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_holding",
    targetEntityId: "ent_gamma",
    type: "management_fee",
    amount: 280000,
    currency: "MAD",
    convertedAmountMAD: 280000,
    date: "2026-09-01",
    period: "2026-09",
    description: "Honoraires d'ingénierie financière et négociation bancaire",
    status: "eliminated",
    isRecurring: true,
    reconciliationNotes: "Élimination automatique appliquée",
    discrepancyAmount: 0,
  },
  {
    id: "ict_006",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_alpha",
    targetEntityId: "ent_gamma",
    type: "shared_services",
    amount: 180000,
    currency: "MAD",
    convertedAmountMAD: 180000,
    date: "2026-07-20",
    period: "2026-07",
    description: "Mise à disposition ingénieurs automatisation & cybersécurité",
    status: "matched",
    isRecurring: false,
    discrepancyAmount: 0,
  },
];

export const DEMO_ELIMINATIONS: EliminationEntry[] = [
  {
    id: "elm_001",
    groupId: "grp_atlas_01",
    period: "2026-09",
    account: "708100 / 618100 - Management Fees",
    debit: 1050000, // Total management fees holding
    credit: 1050000,
    sourceEntityId: "ent_holding",
    targetEntityId: "Filiales (Alpha, Beta, Gamma)",
    eliminationType: "management_fee",
    status: "eliminated",
    notes: "Élimination intégrale des produits et charges de gestion interne intra-groupe",
  },
  {
    id: "elm_002",
    groupId: "grp_atlas_01",
    period: "2026-09",
    account: "248000 / 148000 - Prêts & Dettes Intercompany",
    debit: 1500000, // Prêt Holding à SPV Delta
    credit: 1500000,
    sourceEntityId: "ent_holding",
    targetEntityId: "ent_delta",
    eliminationType: "intercompany_loan",
    status: "eliminated",
    notes: "Neutralisation de la créance d'actif Holding contre la dette financière de passif SPV Delta",
  },
  {
    id: "elm_003",
    groupId: "grp_atlas_01",
    period: "2026-09",
    account: "708800 / 618800 - Refacturations de charges partagées",
    debit: 680000,
    credit: 680000,
    sourceEntityId: "ent_alpha",
    targetEntityId: "ent_beta / ent_gamma",
    eliminationType: "cost_recharge",
    status: "eliminated",
    notes: "Annulation des flux de refacturation informatique et ingénierie interne",
  },
];

export const DEMO_DEBT_FACILITIES: DebtFacility[] = [
  {
    id: "dbt_001",
    entityId: "ent_gamma",
    lenderName: "Banque Centrale Populaire (BCP)",
    facilityType: "bank_loan",
    originalAmount: 6000000,
    outstandingAmount: 4200000,
    currency: "MAD",
    interestRatePct: 5.75,
    maturityDate: "2029-06-30",
    annualService: 980000,
    covenantDescription: "Dette Financière Nette / EBITDA < 4.0x (Actuel : 4.5x - Surveillance requise)",
    collateralNotes: "Nantissement matériel industriel et hypothèque usine",
  },
  {
    id: "dbt_002",
    entityId: "ent_beta",
    lenderName: "BNP Paribas Commercial",
    facilityType: "credit_line",
    originalAmount: 3500000,
    outstandingAmount: 2800000,
    currency: "EUR",
    interestRatePct: 4.80,
    maturityDate: "2027-12-31",
    annualService: 450000,
    covenantDescription: "DSO < 75 jours (Non respecté : 88 jours au T3)",
    collateralNotes: "Cession Dailly de créances commerciales",
  },
  {
    id: "dbt_003",
    entityId: "ent_alpha",
    lenderName: "Attijariwafa Bank",
    facilityType: "leasing",
    originalAmount: 2500000,
    outstandingAmount: 1400000,
    currency: "MAD",
    interestRatePct: 5.20,
    maturityDate: "2028-03-31",
    annualService: 360000,
    covenantDescription: "Fonds propres > 5 000 000 MAD",
    collateralNotes: "Clause de réserve de propriété serveurs & routeurs",
  },
  {
    id: "dbt_004",
    entityId: "ent_delta",
    lenderName: "Atlas Alliance Holding",
    facilityType: "shareholder_loan",
    originalAmount: 1500000,
    outstandingAmount: 1500000,
    currency: "MAD",
    interestRatePct: 3.50,
    maturityDate: "2031-12-31",
    annualService: 52500,
    covenantDescription: "Remboursement subordonné à la mise en service commercial",
    collateralNotes: "Dette junior intra-groupe (éliminée en consolidation)",
  },
];

export const DEMO_CAPEX_ITEMS: CapexItem[] = [
  {
    id: "cpx_001",
    entityId: "ent_gamma",
    assetProjectId: "ast_gamma_1",
    name: "Ligne d'assemblage automatisée Robotique V4",
    category: "equipment",
    supplier: "Kuka Industrial Systems",
    budgetAmount: 2500000,
    committedAmount: 2500000,
    spentAmount: 1600000,
    remainingAmount: 900000,
    expectedPaymentDate: "2026-10-25", // 30 prochains jours
    fundingSource: "bank_debt",
    status: "committed",
  },
  {
    id: "cpx_002",
    entityId: "ent_delta",
    assetProjectId: "ast_delta_1",
    name: "Onduleurs et conteneurs batteries BESS 5MWh",
    category: "equipment",
    supplier: "Sungrow Power Tech",
    budgetAmount: 1400000,
    committedAmount: 1400000,
    spentAmount: 600000,
    remainingAmount: 800000,
    expectedPaymentDate: "2026-11-15", // 60 jours
    fundingSource: "intercompany_loan",
    status: "committed",
  },
  {
    id: "cpx_003",
    entityId: "ent_gamma",
    assetProjectId: "ast_gamma_1",
    name: "Rénovation toiture et isolation thermique usine",
    category: "construction",
    supplier: "Bâtiment Pro Casablanca",
    budgetAmount: 1300000,
    committedAmount: 1300000,
    spentAmount: 800000,
    remainingAmount: 500000,
    expectedPaymentDate: "2026-12-20",
    fundingSource: "cash",
    status: "committed",
  },
  {
    id: "cpx_004",
    entityId: "ent_alpha",
    assetProjectId: "ast_alpha_1",
    name: "Extension baie de stockage NVMe Tier-3",
    category: "technology",
    supplier: "Dell Enterprise",
    budgetAmount: 400000,
    committedAmount: 400000,
    spentAmount: 280000,
    remainingAmount: 120000,
    expectedPaymentDate: "2026-10-10",
    fundingSource: "cash",
    status: "approved",
  },
];

export const DEMO_COST_ALLOCATIONS: CostAllocationRule[] = [
  {
    id: "all_001",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_holding",
    costPoolName: "Frais de Direction Générale, Juridique et DAF Groupe",
    annualPoolAmount: 650000,
    method: "revenue_pct",
    splits: [
      { entityId: "ent_alpha", percentage: 46.8, allocatedAmount: 304200 },
      { entityId: "ent_beta", percentage: 30.0, allocatedAmount: 195000 },
      { entityId: "ent_gamma", percentage: 23.2, allocatedAmount: 150800 },
    ],
    active: true,
  },
  {
    id: "all_002",
    groupId: "grp_atlas_01",
    sourceEntityId: "ent_alpha",
    costPoolName: "Infrastructure Cloud Centrale & Sécurité Groupe",
    annualPoolAmount: 240000,
    method: "fixed_pct",
    splits: [
      { entityId: "ent_alpha", percentage: 40.0, allocatedAmount: 96000 },
      { entityId: "ent_beta", percentage: 35.0, allocatedAmount: 84000 },
      { entityId: "ent_gamma", percentage: 25.0, allocatedAmount: 60000 },
    ],
    active: true,
  },
];

export const DEMO_MANAGEMENT_FEE_RULES: ManagementFeeRule[] = [
  {
    id: "mfr_001",
    holdingEntityId: "ent_holding",
    subsidiaryEntityId: "ent_alpha",
    calculationBasis: "pct_revenue",
    rateOrAmount: 1.5, // 1.5% du CA
    annualBilledMAD: 427500,
    annualCollectedMAD: 427500,
    outstandingMAD: 0,
    status: "active",
  },
  {
    id: "mfr_002",
    holdingEntityId: "ent_holding",
    subsidiaryEntityId: "ent_beta",
    calculationBasis: "fixed_monthly",
    rateOrAmount: 25000, // 25k MAD / mois
    annualBilledMAD: 300000,
    annualCollectedMAD: 180000,
    outstandingMAD: 120000, // Impayé en attente de trésorerie
    status: "active",
  },
  {
    id: "mfr_003",
    holdingEntityId: "ent_holding",
    subsidiaryEntityId: "ent_gamma",
    calculationBasis: "pct_ebitda",
    rateOrAmount: 15.0,
    annualBilledMAD: 138000,
    annualCollectedMAD: 138000,
    outstandingMAD: 0,
    status: "active",
  },
];

export const DEMO_SHAREHOLDERS: ShareholderCapital[] = [
  {
    id: "sh_001",
    entityId: "ent_holding",
    shareholderName: "Famille Fondatrice & Associés",
    ownershipPct: 75.0,
    shareCapitalAmount: 15000000,
    currentAccountBalance: 3200000,
    shareholderType: "individual",
  },
  {
    id: "sh_002",
    entityId: "ent_holding",
    shareholderName: "Maghreb Private Equity Fund III",
    ownershipPct: 25.0,
    shareCapitalAmount: 5000000,
    currentAccountBalance: 0,
    shareholderType: "institution",
  },
  {
    id: "sh_003",
    entityId: "ent_beta",
    shareholderName: "Partenaire Commercial Européen",
    ownershipPct: 20.0,
    shareCapitalAmount: 1200000,
    currentAccountBalance: 450000,
    shareholderType: "co_investor",
  },
  {
    id: "sh_004",
    entityId: "ent_delta",
    shareholderName: "Gulf Renewable Ventures",
    ownershipPct: 40.0,
    shareCapitalAmount: 2000000,
    currentAccountBalance: 1000000,
    shareholderType: "co_investor",
  },
];
