"use client";

import * as React from "react";
import { AppShell } from "@/components/layout/AppShell";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { KPICard } from "@/components/ui/KPICard";
import { useGroup } from "@/lib/group/GroupContext";
import { useLanguage } from "@/lib/i18n/LanguageContext";
import {
  PieChart,
  TrendingUp,
  AlertTriangle,
  ChevronDown,
  ChevronRight,
  Layers,
} from "lucide-react";

interface BudgetCategory {
  id: string;
  name: string;
  nameEn: string;
  budgetMAD: number;
  actualMAD: number;
  entities: {
    entityId: string;
    entityName: string;
    budgetMAD: number;
    actualMAD: number;
  }[];
}

const mockBudgetCategories: BudgetCategory[] = [
  {
    id: "cat_rev",
    name: "Chiffre d'Affaires Brut",
    nameEn: "Gross Consolidated Revenue",
    budgetMAD: 60500000,
    actualMAD: 62050000,
    entities: [
      { entityId: "ent_alpha", entityName: "Entity Alpha", budgetMAD: 27500000, actualMAD: 28500000 },
      { entityId: "ent_beta", entityName: "Entity Beta", budgetMAD: 19000000, actualMAD: 18200000 },
      { entityId: "ent_gamma", entityName: "Entity Gamma", budgetMAD: 14000000, actualMAD: 14100000 },
      { entityId: "ent_holding", entityName: "Atlas Holding", budgetMAD: 1250000, actualMAD: 1250000 },
    ],
  },
  {
    id: "cat_cogs",
    name: "Coût des Marchandises & Matières (COGS)",
    nameEn: "Cost of Goods Sold (COGS)",
    budgetMAD: 31200000,
    actualMAD: 32600000,
    entities: [
      { entityId: "ent_alpha", entityName: "Entity Alpha", budgetMAD: 11000000, actualMAD: 11500000 },
      { entityId: "ent_beta", entityName: "Entity Beta", budgetMAD: 10500000, actualMAD: 11200000 },
      { entityId: "ent_gamma", entityName: "Entity Gamma", budgetMAD: 9700000, actualMAD: 9900000 },
    ],
  },
  {
    id: "cat_payroll",
    name: "Masse Salariale & Charges Sociales",
    nameEn: "Payroll & Social Benefits",
    budgetMAD: 12400000,
    actualMAD: 12850000,
    entities: [
      { entityId: "ent_alpha", entityName: "Entity Alpha", budgetMAD: 5800000, actualMAD: 6100000 },
      { entityId: "ent_beta", entityName: "Entity Beta", budgetMAD: 3200000, actualMAD: 3400000 },
      { entityId: "ent_gamma", entityName: "Entity Gamma", budgetMAD: 2800000, actualMAD: 2750000 },
      { entityId: "ent_holding", entityName: "Atlas Holding", budgetMAD: 600000, actualMAD: 600000 },
    ],
  },
  {
    id: "cat_opex",
    name: "Autres Charges Externes (OPEX)",
    nameEn: "Operating Expenses (OPEX)",
    budgetMAD: 4200000,
    actualMAD: 4700000,
    entities: [
      { entityId: "ent_beta", entityName: "Entity Beta", budgetMAD: 1200000, actualMAD: 1550000 },
      { entityId: "ent_gamma", entityName: "Entity Gamma", budgetMAD: 1400000, actualMAD: 1500000 },
      { entityId: "ent_alpha", entityName: "Entity Alpha", budgetMAD: 1200000, actualMAD: 1250000 },
      { entityId: "ent_holding", entityName: "Atlas Holding", budgetMAD: 400000, actualMAD: 400000 },
    ],
  },
];

export default function GroupBudgetPage() {
  const { consolidationCurrency } = useGroup();
  const { t, locale, formatMoney } = useLanguage();

  const [expandedCategories, setExpandedCategories] = React.useState<Record<string, boolean>>({
    cat_opex: true,
  });

  const toggleCategory = (id: string) => {
    setExpandedCategories((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  return (
    <AppShell
      title={t.nav.consolidatedBudget}
      subtitle={locale === "en" ? `Consolidated budget tracking with hierarchical drilldown: Group → Entity → Expense Category • Currency: ${consolidationCurrency}` : `Suivi budgétaire consolidé avec forage hiérarchique : Groupe → Entité → Catégorie de charges • Devise : ${consolidationCurrency}`}
    >
      {/* Top 4 Budget KPIs */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <KPICard
          title={locale === "en" ? "Revenue vs Target" : "Chiffre d'Affaires vs Budget"}
          value="+1 550 000 MAD"
          badge="+2.5% ahead"
          badgeVariant="green"
          description={locale === "en" ? "Commercial traction on Alpha" : "Traction commerciale Alpha"}
          icon={<TrendingUp className="w-4 h-4 text-emerald-600" />}
          sparklineData={[60, 60.5, 61, 61.2, 61.8, 62]}
        />

        <KPICard
          title={locale === "en" ? "OPEX Budget Overrun" : "Dépassement Charges OPEX"}
          value="+500 000 MAD"
          badge="+11.9% overrun"
          badgeVariant="rose"
          description={locale === "en" ? "70% generated by Entity Beta" : "Généré à 70% par Entity Beta"}
          icon={<AlertTriangle className="w-4 h-4 text-rose-600" />}
          sparklineData={[4.2, 4.3, 4.4, 4.5, 4.6, 4.7]}
        />

        <KPICard
          title={locale === "en" ? "Consolidated Payroll" : "Masse Salariale Consolidée"}
          value="12 850 000 MAD"
          badge="+3.6% drift"
          badgeVariant="warning"
          description={locale === "en" ? "Engineering hires ahead of schedule" : "Recrutements techniques anticipés"}
          icon={<PieChart className="w-4 h-4 text-amber-600" />}
          sparklineData={[12.4, 12.5, 12.6, 12.7, 12.8, 12.85]}
        />

        <KPICard
          title={locale === "en" ? "Overall Budget Discipline" : "Respect Global Enveloppes"}
          value="96.2%"
          badge={locale === "en" ? "Compliant" : "Conforme"}
          badgeVariant="green"
          description={locale === "en" ? "Holding budget controls verified" : "Cohérence budgétaire maintenue"}
          icon={<Layers className="w-4 h-4 text-blue-600" />}
          sparklineData={[94, 94.5, 95, 95.8, 96, 96.2]}
        />
      </div>

      {/* Drilldown Table: Group -> Entity -> Category */}
      <Card
        title={locale === "en" ? "Budgetary Control & Subsidiary Drilldown" : "Contrôle Budgétaire & Forage par Filiale (Drilldown)"}
        subtitle={locale === "en" ? "Click any category to isolate the exact entity driving the budgetary variance" : "Cliquez sur une catégorie pour identifier précisément l'entité responsable de l'écart"}
      >
        <div className="overflow-x-auto">
          <table className="w-full text-xs border border-slate-200/80 rounded-xl overflow-hidden">
            <thead className="bg-slate-100 text-slate-800 font-bold border-b border-slate-200">
              <tr>
                <th className="p-3 text-left w-72">{locale === "en" ? "Category / Subsidiary" : "Catégorie Budgétaire / Filiale"}</th>
                <th className="p-3 text-right">{locale === "en" ? "Allocated Budget" : "Budget Alloué"}</th>
                <th className="p-3 text-right">{locale === "en" ? "Actual Recorded" : "Réalisé Constaté"}</th>
                <th className="p-3 text-right">{locale === "en" ? "Variance (MAD)" : "Écart (MAD)"}</th>
                <th className="p-3 text-center">{locale === "en" ? "Variance (%)" : "Écart (%)"}</th>
                <th className="p-3 text-center">{locale === "en" ? "Status" : "Statut"}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {mockBudgetCategories.map((cat) => {
                const isExpanded = expandedCategories[cat.id];
                const varianceMAD = cat.actualMAD - cat.budgetMAD;
                const variancePct = ((varianceMAD / cat.budgetMAD) * 100).toFixed(1);
                const isOverrun = cat.id !== "cat_rev" ? varianceMAD > 0 : varianceMAD < 0;

                return (
                  <React.Fragment key={cat.id}>
                    {/* Parent Category Row */}
                    <tr
                      onClick={() => toggleCategory(cat.id)}
                      className="bg-slate-50 hover:bg-slate-100/80 cursor-pointer font-bold select-none transition-colors"
                    >
                      <td className="p-3 text-slate-900 flex items-center gap-2">
                        <button className="text-slate-400">
                          {isExpanded ? (
                            <ChevronDown className="w-4 h-4" />
                          ) : (
                            <ChevronRight className="w-4 h-4" />
                          )}
                        </button>
                        <span>{locale === "en" ? cat.nameEn : cat.name}</span>
                      </td>

                      <td className="p-3 text-right font-mono text-slate-700 font-tabular">
                        {formatMoney(cat.budgetMAD)} MAD
                      </td>

                      <td className="p-3 text-right font-mono text-slate-900 font-bold font-tabular">
                        {formatMoney(cat.actualMAD)} MAD
                      </td>

                      <td
                        className={`p-3 text-right font-mono font-bold font-tabular ${
                          isOverrun ? "text-rose-600" : "text-emerald-700"
                        }`}
                      >
                        {varianceMAD >= 0 ? "+" : ""}
                        {formatMoney(varianceMAD)} MAD
                      </td>

                      <td className="p-3 text-center font-mono font-tabular">
                        <span
                          className={`px-2 py-0.5 rounded text-[11px] font-bold ${
                            isOverrun
                              ? "bg-rose-50 text-rose-700 border border-rose-200/60"
                              : "bg-emerald-50 text-emerald-700 border border-emerald-200/60"
                          }`}
                        >
                          {varianceMAD >= 0 ? "+" : ""}
                          {variancePct}%
                        </span>
                      </td>

                      <td className="p-3 text-center">
                        <Badge variant={isOverrun ? "rose" : "green"} size="sm" dot>
                          {isOverrun ? (locale === "en" ? "Overrun" : "Dépassement") : (locale === "en" ? "Compliant" : "Conforme")}
                        </Badge>
                      </td>
                    </tr>

                    {/* Sub-Rows: Entities under this category */}
                    {isExpanded &&
                      cat.entities.map((sub) => {
                        const subVariance = sub.actualMAD - sub.budgetMAD;
                        const subPct = ((subVariance / sub.budgetMAD) * 100).toFixed(1);
                        const subIsOverrun = cat.id !== "cat_rev" ? subVariance > 0 : subVariance < 0;

                        return (
                          <tr key={sub.entityId} className="hover:bg-slate-50/70 bg-white transition-colors">
                            <td className="p-3 pl-10 text-slate-700 font-medium flex items-center gap-2">
                              <span className="w-1.5 h-1.5 rounded-full bg-slate-300" />
                              <span className="font-semibold text-slate-800">{sub.entityName}</span>
                            </td>

                            <td className="p-3 text-right font-mono text-slate-500 font-tabular">
                              {formatMoney(sub.budgetMAD)} MAD
                            </td>

                            <td className="p-3 text-right font-mono text-slate-800 font-tabular font-medium">
                              {formatMoney(sub.actualMAD)} MAD
                            </td>

                            <td
                              className={`p-3 text-right font-mono font-tabular ${
                                subIsOverrun ? "text-rose-600 font-bold" : "text-emerald-700 font-medium"
                              }`}
                            >
                              {subVariance >= 0 ? "+" : ""}
                              {formatMoney(subVariance)} MAD
                            </td>

                            <td className="p-3 text-center font-mono text-xs text-slate-600 font-tabular">
                              {subVariance >= 0 ? "+" : ""}
                              {subPct}%
                            </td>

                            <td className="p-3 text-center">
                              {subIsOverrun && Math.abs(subVariance) > 200000 && (
                                <span className="text-[10px] text-rose-600 font-bold bg-rose-50 px-2 py-0.5 rounded border border-rose-200/60">
                                  {locale === "en" ? "Variance Source" : "Source de l'écart"}
                                </span>
                              )}
                            </td>
                          </tr>
                        );
                      })}
                  </React.Fragment>
                );
              })}
            </tbody>
          </table>
        </div>
      </Card>
    </AppShell>
  );
}
